apiVersion: apps/v1
kind: Deployment
metadata:
  name: 255-lab3-app
  namespace: w255
  labels:
    app: 255-lab3-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 255-lab3-app
  template:
    metadata:
      labels:
        app: 255-lab3-app
    spec:
      initContainers:
        - name: init-verify-redis-service-dns
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -vz redis-service 6379; do echo 'waiting for redis service from DNS'; sleep 2; done",
            ]
        - name: init-verify-redis-ready
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until (printf 'PING\r\n';) | nc redis-service 6379; do echo 'waiting for redis to PONG'; sleep 1; done",
            ]
      containers:
        - name: 255-lab3-app
          image: 255-lab3-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10