apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: w255
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis